POSTGRES:
   HOST: 127.0.0.1
   USER: user
   PASSWORD: password
   PORT: 5433
   DB: db

REDIS:
   HOST: 127.0.0.1
   PORT: 6379

WEBSOCKETS:
   HOST: 127.0.0.1
   PORT: 8001

FINDCLONE:
   LOGIN: ""
   PASSWORD: ""

VK_API:
VK_USER_KEY: